---
- hosts: all
  become: yes
  tasks:
    - name: create 'ubuntu' user
      ansible.buildin.user: 
        name: ubuntu 
        append: yes 
        state: present 
        createhome: yes 
        shell: /bin/bash

    - name: allow 'ubuntu' to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=ubuntu key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
