---
- hosts: all
  become: yes
  tasks:
    - name: create Docker config directory
      ansible.buildin.file: 
        path: /etc/docker 
        state: directory

    - name: changing Docker to systemd driver
      copy:
        dest: "/etc/docker/daemon.json"
        content: |
          {
          "exec-opts": ["native.cgroupdriver=systemd"]
          }

    - name: install Docker
      ansible.buildin.apt:
        name: docker.io
        state: present
        update_cache: true

    - name: install APT Transport HTTPS
      ansible.buildin.apt:
        name: apt-transport-https
        state: present

    - name: add Kubernetes apt-key
      ansible.buildin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: add Kubernetes' APT repository
      ansible.buildin.apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'

    - name: install kubelet
      ansible.buildin.apt:
        name: kubelet=1.22.4-00
        state: present
        update_cache: true

    - name: install kubeadm
      ansible.buildin.apt:
        name: kubeadm=1.22.4-00
        state: present

- hosts: control_plane
  become: yes
  tasks:
    - name: install kubectl
      ansible.buildin.apt:
        name: kubectl=1.22.4-00
        state: present
        force: yes